run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  govet:
    enable:
      - shadow
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code (includes shadow checking)
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - typecheck     # Type checking
    - unused        # Check for unused code
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Check cyclomatic complexity
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
  disable: []

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Allow variable shadowing in test files
    - path: _test\.go
      text: "shadow:"
  # Don't hide multiple issues in the same file
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true